#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-sugar
Version  : 0.9.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/3e/6a/a3f909083079d03bde11d06ab23088886bbe25f2c97fbe4bb865e2bf05bc/pytest-sugar-0.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/3e/6a/a3f909083079d03bde11d06ab23088886bbe25f2c97fbe4bb865e2bf05bc/pytest-sugar-0.9.1.tar.gz
Summary  : py.test is a plugin for py.test that changes the default look and feel of py.test (e.g. progressbar, show tests that fail instantly).
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pytest-sugar-python3
Requires: pytest-sugar-license
Requires: pytest-sugar-python
Requires: pytest
Requires: termcolor
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : termcolor
BuildRequires : tox
BuildRequires : virtualenv

%description
# pytest-sugar
[![](https://travis-ci.org/Frozenball/pytest-sugar.svg?branch=master)](https://travis-ci.org/Frozenball/pytest-sugar) ![](https://img.shields.io/pypi/v/pytest-sugar.svg)

%package license
Summary: license components for the pytest-sugar package.
Group: Default

%description license
license components for the pytest-sugar package.


%package python
Summary: python components for the pytest-sugar package.
Group: Default
Requires: pytest-sugar-python3

%description python
python components for the pytest-sugar package.


%package python3
Summary: python3 components for the pytest-sugar package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytest-sugar package.


%prep
%setup -q -n pytest-sugar-0.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534430852
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pytest-sugar
cp LICENSE %{buildroot}/usr/share/doc/pytest-sugar/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/pytest-sugar/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
