#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-sugar
Version  : 0.9.2
Release  : 5
URL      : https://files.pythonhosted.org/packages/55/59/f02f78d1c80f7e03e23177f60624c8106d4f23d124c921df103f65692464/pytest-sugar-0.9.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/55/59/f02f78d1c80f7e03e23177f60624c8106d4f23d124c921df103f65692464/pytest-sugar-0.9.2.tar.gz
Summary  : pytest-sugar is a plugin for pytest that changes the default look and feel of pytest (e.g. progressbar, show tests that fail instantly).
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pytest-sugar-license = %{version}-%{release}
Requires: pytest-sugar-python = %{version}-%{release}
Requires: pytest-sugar-python3 = %{version}-%{release}
Requires: packaging
Requires: pytest
Requires: termcolor
BuildRequires : buildreq-distutils3
BuildRequires : packaging
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : termcolor
BuildRequires : tox
BuildRequires : virtualenv

%description
# pytest-sugar
[![](https://travis-ci.org/Frozenball/pytest-sugar.svg?branch=master)](https://travis-ci.org/Frozenball/pytest-sugar) ![](https://img.shields.io/pypi/v/pytest-sugar.svg)

%package license
Summary: license components for the pytest-sugar package.
Group: Default

%description license
license components for the pytest-sugar package.


%package python
Summary: python components for the pytest-sugar package.
Group: Default
Requires: pytest-sugar-python3 = %{version}-%{release}

%description python
python components for the pytest-sugar package.


%package python3
Summary: python3 components for the pytest-sugar package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytest-sugar package.


%prep
%setup -q -n pytest-sugar-0.9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541732902
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-sugar
cp LICENSE %{buildroot}/usr/share/package-licenses/pytest-sugar/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-sugar/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
